# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

default_containers: &defaultCon
  docker:
  - image: circleci/node:13.8.0

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
# orbs:
#   node: circleci/node@4.7

jobs:
  build:
    <<: *defaultCon
    steps:
      - checkout
      - run: npm i
      - save_cache:
          paths:
            - "/src/node_modules"
          key: "npm-packages"
      - run: npm run lint

  test:
    <<: *defaultCon
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm run test


  analyze:
    <<: *defaultCon
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm audit


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  myNodeWorkflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
      - test:
        requires:
          - build
      - analyze:
          requires:
            - test
          # # This is the node version to use for the `cimg/node` tag
          # # Relevant tags can be found on the CircleCI Developer Hub
          # # https://circleci.com/developer/images/image/cimg/node
          # version: '16.10'
          # # If you are using yarn, change the line below from "npm" to "yarn"
          # pkg-manager: npm
